name = "heictopdf"
compatibility_date = "2025-08-05"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 配置
pages_build_output_dir = ".vercel/output/static"

# 环境变量配置 - 只包含公开变量
[vars]
NEXT_PUBLIC_APP_URL = "https://heic-to-pdf.pro"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_YW1hemluZy1hbnRlYXRlci04Mi5jbGVyay5hY2NvdW50cy5kZXYk"
# 敏感变量请在 Cloudflare Pages 控制台中配置：
# - DATABASE_URL
# - HASHID_SALT  
# - CLERK_SECRET_KEY
# - CONVERTAPI_SECRET

# 生产环境变量
[env.production]
[env.production.vars]
NEXT_PUBLIC_APP_URL = "https://heic-to-pdf.pro"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_YW1hemluZy1hbnRlYXRlci04Mi5jbGVyay5hY2NvdW50cy5kZXYk"

# 预览环境变量  
[env.preview]
[env.preview.vars]
NEXT_PUBLIC_APP_URL = "https://preview.heic-to-pdf.pro"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_YW1hemluZy1hbnRlYXRlci04Mi5jbGVyay5hY2NvdW50cy5kZXYk"